#!/usr/bin/env bash
#Bash script that displays Best School 10 times using while and Hi at ninth times
x=1
while [ $x -le 10 ]
do
  echo "Best School"
  if ((x == 9))
  then
    echo "Hi"
  fi
  x=$(( x + 1 ))
done

