#!/usr/bin/env bash

FILE=school
if test -f "$FILE";
then 
	echo "$FILE file exists"
	if [ -s $FILE ]
	then
     		echo "$FILE file is not empty"
		echo "$FILE is a regular"
	else
     		echo "$FILE file is empty"
		echo "$FILE is a regular"
	fi
elif [ -d $FILE ]
then
	echo "$FILE file exists"
	echo "$FILE file is not empty"
else
	echo "$FILE file does not exist"
fi
