#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it’s executed on.
ip_addresses=$(hostname -I)
ip_addresses=("${ip_addresses//" "/ }")
for ip in "${ip_addresses[@]}";
do
      printf "%s""$ip\n"
done
